Implement embedded_nal UpdFullStack
quartiq/smoltcp-nal pull request #39
Opened 2022-02-09 19:53 UTC by svrotter

Implement embedded_nal UpdFullStack in order to be able to bind to a specific socket

2022-02-10 08:31 UTC, ryan-summers requested changes

2022-02-10 08:31 UTC, ryan-summers commented on src/lib.rs
> +            .next()
I think you can replace `filter().next()` with a `find()` call instead

2022-02-10 08:31 UTC, ryan-summers commented on src/lib.rs
> +            .map_err(|_| NetworkError::ConnectionFailure)?;
What happens when a user has already called `connect()`? Does it generate a smoltcp error?

2022-02-10 08:31 UTC, ryan-summers commented on src/lib.rs
> +                socket.destination = IpEndpoint::new(
This is not what we want. This would break the `UdpClientStack` by removing any information about our remote connection.

Refactor this to be:
```rust
let destination = match remote {
    embedded_nal::SocketAddr::V4(addr) => {
        IpEndpoint::new(IpAddress::v4(octets[0], octets[1], octets[2], octets[3]), addr.port())
    }
}

2022-02-10 08:32 UTC, ryan-summers commented on src/lib.rs
> +            .map_err(|_| NetworkError::ConnectionFailure)?;
Docs indicate that `smoltcp` will generate `Err(Error::Illegal)` which we map to a  `ConnectionFailure`, so that seems acceptable to me.

2022-02-11 16:43 UTC, svrotter commented on src/lib.rs
> +            .next()
Did that

2022-02-11 16:43 UTC, svrotter commented on src/lib.rs
> +                socket.destination = IpEndpoint::new(
Did that

2022-02-11 16:43 UTC, svrotter commented
Tested the additional changes on Stabilizer today and encountered no issues

2022-02-11 16:48 UTC, ryan-summers commented
Sounds good! I think the only thing we're missing is a CHANGELOG.md entry for the additions, but other than that looks good to merge

2022-02-11 17:58 UTC, merged