Adding support for TCP port randomization
quartiq/smoltcp-nal pull request #5
Opened 2021-03-09 13:30 UTC by ryan-summers

This PR fixes #4 by using the WyRand algorithm to randomize local TCP support selection.

**TODO**:
- [x] Test randomization on hardware

2021-03-10 03:06 UTC, dnadlinger commented
Ah, nice, I'll test that it doesn't horribly break things on hardware later this week as well then. (I don't think I'll get around to testing multiple sockets, etc., though.)

2021-04-14 13:16 UTC, irwineffect requested changes

2021-04-14 13:16 UTC, irwineffect commented on src/lib.rs
> +            .and_then(|index| Some(used_ports.swap_remove(index)));
Should we `unwrap()` the option that is returned by `position()` rather than use `and_then()`? Not finding the port would mean we've made a logical error in the code, right?

2021-04-15 10:08 UTC, ryan-summers commented on src/lib.rs
> +            };
You cannot cast a slice or array of [u8] into a u16 either using `as` or `From` to my knowledge due to endianness issues. You have to explicitly construct with known byte ordering. For us, it doesn't matter, but that's why this is done like this.

2021-04-15 15:37 UTC, irwineffect commented on src/lib.rs
> +            };
Ah, from the docs I read that Wyrand returns 64 bits of data, I assumed that meant a u64, totally missed that the interface is `[u8;8]`. This makes sense now.

2021-04-15 15:39 UTC, irwineffect approved these changes

2021-04-15 17:00 UTC, merged