Feature/dhcp support
quartiq/smoltcp-nal pull request #7
Opened 2021-03-12 11:46 UTC by ryan-summers

2021-03-13 18:54 UTC, irwineffect requested changes

2021-03-13 18:54 UTC, irwineffect commented on src/lib.rs
> +            .is_unspecified()
We perform this same check in multiple places, perhaps put into a function?

2021-03-13 18:54 UTC, irwineffect commented on src/lib.rs
Do you actually need `RefCell` for all these? I think you can get away with just a `Cell`.

2021-03-15 10:30 UTC, ryan-summers commented on src/lib.rs
`Cell` forces move/copy semantics when accessing internal data, whereas `RefCell` allows us to borrow internal contents with dynamic check rules. If we wanted to use a Cell, we would have to either copy the name servers when reading them or we would have to move them out of the data type. I think RefCell is still the right approach here for now

2021-03-15 10:34 UTC, ryan-summers commented on src/lib.rs
> +        handles: &[smoltcp::socket::SocketHandle],
I don't think we can feasibly do ownership (since this is a slice) until const-generics stabilize. I'll add a note in the docs that there's a contract that the user does not use the socket handles after providing them.

2021-03-16 12:58 UTC, irwineffect commented on src/lib.rs
> +        handles: &[smoltcp::socket::SocketHandle],
You could force the user to create a `Vec` and take ownership of that, but yeah that's annoying.

2021-03-16 13:01 UTC, irwineffect approved these changes

2021-03-17 13:49 UTC, merged